services:
  - type: web
    name: music-games-solfeo
    env: python
    rootDir: music_games
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11